DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS households CASCADE;
DROP TABLE IF EXISTS user_households CASCADE;
DROP TABLE IF EXISTS shops CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS recipes CASCADE;
DROP TABLE IF EXISTS recipe_items CASCADE;